module RuZip
  class Archive
    def self.new: (IO | path) -> instance
    def len: -> Integer
    def by_index: (Integer) -> File
    def by_name: (String) -> File
  end

  class File
    def name: -> String

    # The size of decompressed file
    def size: -> Integer
    def last_modified: -> (Time | nil)

    # Reads contents and returns it as BINARY string
    def read: -> String
  end

  class Writer
    def self.new: (String) -> instance
    def finish: -> Archive
    def start_file: (String) -> void
    def write: (String) -> void
  end
end
