[package]
name = "ruzip"
version = "0.1.0"
edition = "2021"
authors = ["Kitaiti Makoto <KitaitiMakoto@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6" }
zip = "0.6.6"
